### ISSUE TITLE
Example HDF5?

### ISSUE THREAD

**Issue by DANAJK** [ETSInitiative/PRDdefinition#11]
Any chance you could make available a copy of the HDF5 file that should be output?

**Comment by KrisThielemans** [comment]
At present, the generator is written with random number generation, but I can give a sample. Note that this repo is quite preliminary, so a lot of the fields won't be there.

[test.h5.gz](https://github.com/ETSInitiative/PRDdefinition/files/13291088/test.h5.gz)

I have never looked at the HDF5 structure myself, so that'll be interesting. Note that feedback on how yardl encodes information to HDF5 might belong best in https://github.com/microsoft/yardl/

**Comment by DANAJK** [comment]
Thanks.
